# Generated by Django 3.2.15 on 2022-08-30 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20220829_0411'),
        ('reviews', '0006_auto_20220830_1133'),
    ]

    operations = [
    ]
