# Generated by Django 2.2.16 on 2022-08-29 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20220828_1825'),
        ('reviews', '0002_auto_20220829_0156'),
    ]

    operations = [
    ]
